services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
      - ./next-app/next.config.js:/app/next.config.js
      - ./next-app/.env:/app/.env
    restart: always
    ports:
      - 3000:3000
    #expose:
    #  - 3000
    networks:
      - nginx-net  # ← tambahkan ini

networks:
  nginx-net:
    external: true  # ← deklarasikan agar bisa dipakai